name: Publish Package to NPM

on:
  release:
    types: [created]

env:
  NODE_VERSION: 16.x
  REGISTRY_URL: https://registry.npmjs.org

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: ${{env.REGISTRY_URL}}

      - name: Install dependecies
        run: npm ci

      - name: Setting access
        run: npm config set access public

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
